config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get "/admin/candies",             to: "admin/candies#index"
  get "/admin/candies/new",         to: "admin/candies#new"
  get "/admin/candies/:id",         to: "admin/candies#show"
  post "/admin/candies",            to: "admin/candies#create"
  get "/admin/candies/:id/edit",    to: "admin/candies#edit"
  patch "/admin/candies/:id",       to: "admin/candies#update"

  get "/admin/dashboard/:id",       to: "admin/dashboard#show"

  get "/candies",                   to: "candies#index"
  get "/candies/:id",               to: "candies#show"

  get "/categories",                to: "categories#index"
  get "/categories/:id",            to: "categories#show"

  get "/reviews",                   to: "reviews#new"
  post "/reviews",                  to: "reviews#create"

  get "/register",                  to: "users#new"

  get "/login",                     to: "sessions#new"
  post "/login",                    to: "sessions#create"
  delete "/logout",                 to: "sessions#destroy"

  post "/users",                    to: "users#create"
  get "/dashboard",                 to: "users#show"

  post "/carts",                    to: "carts#create"
  get "/cart",                      to: "carts#show"
  put "/cart",                      to: "carts#update"
  delete "/cart",                   to: "carts#destroy"

  get "/orders",                    to: "orders#index"
  post"/orders",                    to: "orders#create"
  get "/orders/:id",                to: "orders#show"

  get "/order_success",             to: "order_success#show"

  get "/custom_candies",            to: "custom_candies#index"
  get "/custom_candies/new",        to: "custom_candies#new"
  get "/custom_candies/:id",        to: "custom_candies#show"
  post "/custom_candies",           to: "custom_candies#create"
  patch "/custom_candies/:id/edit", to: "custom_candies#update"
end

app/models/candy.rb
class Candy < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  attr_accessor :image
  has_many :candy_orders
  has_many :orders, through: :candy_orders
  has_many :reviews

  belongs_to :category
  has_attached_file :image, :path => ":rails_root/public/system/:attachment/:id/:style/:filename", :url => "/system/:attachment/:id/:style/:filename", styles: { favicon: '16x16>', square: '200x200#', medium: '300x300>' }

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :category_id, presence: true
  validates :status, presence: true
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  # before_save :set_image

  def set_image
    if image.nil? || image.empty?
      self.image = "http://www.travelandleisure.com/sites/default/files/styles/1600x1000/public/americancandy1015.jpg"
    end
  end

  def currency
    price / 100.0 if price
  end

  def to_dollars
    number_to_currency(currency)
  end

  def average_rating
    if reviews.last
      (reviews.sum(:rating) / reviews.count.to_f).round(2).to_s + " out of 5"
    else
      "Candy has not yet been rated"
    end
  end

  def retired?
    status == "Discontinued"
  end

  def out_of_stock?
    status == "Out of Stock"
  end
end

app/controllers/admin/candies_controller.rb
class Admin::CandiesController < Admin::AuthorizationController
  def index
    @candies = Candy.all
  end

  def show
    @candy = Candy.find(params[:id])
  end

  def new
    @candy = Candy.new
  end

  def create
    @candy = Candy.new(candy_params)
    if @candy.save
      flash[:success] = "#{@candy.title} created!"
      redirect_to "/admin/candies"
    else
      flash.now[:error] = "All fields are required"
      render :new
    end
  end

  def edit
    @candy = Candy.find(params[:id])
  end

  def update
    candy = Candy.find(params[:id])
    candy.update(candy_params)
    redirect_to admin_candies_path
  end

  private

  def candy_params
    params.require(:candy).permit(
                                 :title,
                                 :description,
                                 :price,
                                 :image,
                                 :status,
                                 :category_id)
  end
end

app/controllers/candies_controller.rb
class CandiesController < ApplicationController
  def index
    @candies = Candy.all
  end

  def show
    @candy = Candy.find(params[:id])
  end
end

app/views/candies/edit.html.erb
<h3>Rate this Candy</h3>
<%= form_for(@candy) do |f| %>
<%= f.label :rating %>
<%= f.text_field :rating %>
<%= f.submit "Submit" %>
<% end %>

<p>Ratings<p>
<% @candy.ratings.each do |rating| %>
  <p><%= rating.rating %></p>
<% end %>

app/views/candies/index.html.erb
<%= render partial: 'partials/flash' %>
<% @candies.each do |candy| %>
  <%= render partial: 'partials/each_candy', locals: {candy: candy} %>
<% end %>

app/views/candies/show.html.erb
<%= render partial: 'partials/flash' %>

<img src="<%= @candy.image %>" />
<h5><%= @candy.title %> </h5>
<p>Description: <%= @candy.description %> </p>
<p>Price: <%= @candy.to_dollars %></p>
<p>Status: <%= @candy.status %></p>
<p>Category: <%= @candy.category.name %></p>
<p>Rating: <%= @candy.average_rating %></p>
<% if @candy.retired? %>
  <div class="center-align">Item no longer available</div>
<% elsif @candy.out_of_stock? %>
  <div class="center-align">Not in Stock</div>
<% else %>
  <div id="<%= @candy.id %>" class="center-align"><%= button_to "Add to Cart", carts_path(candy_id: @candy.id), class: "btn btn-success red" %></div>
<% end %>

<h3>Reviews</h3>
<table class="highlight">
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Review</th>
    </tr>
  </thead>
  <tbody>
    <% @candy.reviews.each do |review| %>
      <tr>
        <td><%= review.name %></td>
        <td><%= review.rating %></td>
        <td><%= review.review %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h5><%= link_to "Review this Candy", reviews_path(candy_id: @candy.id) %></h5>