config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get "/admin/candies",             to: "admin/candies#index"
  get "/admin/candies/new",         to: "admin/candies#new"
  get "/admin/candies/:id",         to: "admin/candies#show"
  post "/admin/candies",            to: "admin/candies#create"
  get "/admin/candies/:id/edit",    to: "admin/candies#edit"
  patch "/admin/candies/:id",       to: "admin/candies#update"

  get "/admin/dashboard/:id",       to: "admin/dashboard#show"

  get "/candies",                   to: "candies#index"
  get "/candies/:id",               to: "candies#show"

  get "/categories",                to: "categories#index"
  get "/categories/:id",            to: "categories#show"

  get "/reviews",                   to: "reviews#new"
  post "/reviews",                  to: "reviews#create"

  get "/register",                  to: "users#new"

  get "/login",                     to: "sessions#new"
  post "/login",                    to: "sessions#create"
  delete "/logout",                 to: "sessions#destroy"

  post "/users",                    to: "users#create"
  get "/dashboard",                 to: "users#show"

  post "/carts",                    to: "carts#create"
  get "/cart",                      to: "carts#show"
  put "/cart",                      to: "carts#update"
  delete "/cart",                   to: "carts#destroy"

  get "/orders",                    to: "orders#index"
  post"/orders",                    to: "orders#create"
  get "/orders/:id",                to: "orders#show"

  get "/order_success",             to: "order_success#show"

  get "/custom_candies",            to: "custom_candies#index"
  get "/custom_candies/new",        to: "custom_candies#new"
  get "/custom_candies/:id",        to: "custom_candies#show"
  post "/custom_candies",           to: "custom_candies#create"
  patch "/custom_candies/:id/edit", to: "custom_candies#update"
end

app/models/cart.rb
class Cart
  include ActionView::Helpers::NumberHelper
  attr_reader :contents

  def initialize(initial_contents = nil)
    @contents = initial_contents || {"candy" => {}, "custom" => {}}
  end

  def add_candy(candy_id, kind_of_candy)
    contents[kind_of_candy][candy_id.to_s] ||= 0
    contents[kind_of_candy][candy_id.to_s] += 1
  end

  def total
    contents["candy"] ? candy = contents["candy"].values.sum : candy = 0
    contents["custom"] ? custom = contents["custom"].values.sum : custom = 0

    candy + custom
  end

  def total_cost
    if contents["candy"] && contents["custom"]
      total = tally_price(contents["candy"]) + tally_price(contents["custom"])
    else
      candy_type = contents["candy"] || contents["custom"]
      total = tally_price(candy_type)
    end
    number_to_currency(total)
  end

  def tally_price(candy_type)
    candy_type.map do |id, quantity|
      candy = find_candy(candy_type, id)
      candy.currency * quantity
    end.sum
  end

  def find_candy(candy_type, id)
    if candy_type == contents["candy"]
      Candy.find(id)
    else
      CustomCandy.find(id)
    end
  end

  def remove_candy(candy)
    if candy.class == Candy
      contents["candy"].delete(candy.id.to_s)
    else
      contents["custom"].delete(candy.id.to_s)
    end
  end

  def find_candy_type(candy)
    if candy.class == Candy
      contents["candy"]
    else
      contents["custom"]
    end
  end

  def adjust_quantity(operator, candy)
    candy_type = find_candy_type(candy)
    if operator == "-"
      candy_type[candy.id.to_s] -= 1 unless candy_type[candy.id] == 1
    else
      candy_type[candy.id.to_s] += 1
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  include CartsHelper

  def create
    if request.referrer.include?("custom_candies")
      candy = CustomCandy.find(params[:id])
      @cart.add_candy(candy.id, "custom")
    else
      candy = Candy.find(params[:candy_id])
      @cart.add_candy(candy.id, "candy")
    end
    session[:cart] = @cart.contents
    flash[:info] = "Cart updated with #{path(candy)}"
    redirect_to :back
  end

  def show
  end

  def update
    if params[:custom_id]
      candy = CustomCandy.find(params[:custom_id])
    else
      candy = Candy.find(params[:candy_id])
    end
    @cart.adjust_quantity(params[:operator], candy)
    flash[:success] = "Quantity for #{path(candy)} has been changed"
    redirect_to cart_path
  end

  def destroy
    if params[:custom_id]
      candy = CustomCandy.find(params[:custom_id])
    else
      candy = Candy.find(params[:candy_id])
    end
    @cart.remove_candy(candy)
    flash[:success] = "Successfully removed #{path(candy)} from your cart."
    redirect_to cart_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def path(candy)
    "<a href=\"/candies/#{candy.id}\">#{candy.title}</a>"
  end
end

app/views/carts/edit.html.erb
<%= form_for(@contents) do |f| %>
<%= f.label :quantity %>
<%= f.text_field :quantity %>
<%= f.submit %>
<% end %>

app/views/carts/show.html.erb
<%= render partial: 'partials/flash' %>

<div>
  <% unless @cart.contents["candy"].empty? && @cart.contents["custom"].empty? %>

  <table class="highlight">
    <thead>
     <tr>
       <th><strong></strong></th>
       <th><strong>Candy</strong></th>
       <th><strong>Description</strong></th>
       <th><strong>Price</strong></th>
       <th><strong>Quantity</strong></th>
       <th><strong></strong></th>
       <th><strong></strong></th>
     </tr>
    </thead>
    <tbody>
    <% @cart.contents["candy"].each do |id, quantity| %>
      <% candy = Candy.find(id) %>
      <tr>
        <td><div id="<%= candy.id %>"><a class="waves-effect waves-light btn red"><%= button_to "Remove", cart_path(candy_id: candy.id), method: "delete" %></a></div></td>
        <td><%= candy.title %></td>
        <td><%= candy.description %></td>
        <td><%= candy.to_dollars %></td>
        <td><%= quantity %></td>
        <td><a class="btn-floating btn-small waves-effect waves-light red center-align"><%= button_to "+", cart_path(candy_id: candy.id, operator: "+"), method: :put %></a></td>
        <td><a class="btn-floating btn-small waves-effect waves-light red center-align"><%= button_to "-", cart_path(candy_id: candy.id, operator: "-"), method: :put unless quantity == 1 %></a></td>
      </tr>
    <% end if @cart.contents["candy"]%>

    <% @cart.contents["custom"].each do |id, quantity| %>
      <% candy = CustomCandy.find(id) %>
      <tr>
        <td><div id="<%= candy.id %>"><a class="waves-effect waves-light btn red"><%= button_to "Remove", cart_path(custom_id: candy.id), method: "delete" %></a></div></td>
        <td><%= candy.title %></td>
        <td><%= candy.describe %></td>
        <td><%= candy.to_dollars %></td>
        <td><%= quantity %></td>
        <td><a class="btn-floating btn-small waves-effect waves-light red center-align"><%= button_to "+", cart_path(custom_id: candy.id, operator: "+"), method: :put %></a></td>
        <td><a class="btn-floating btn-small waves-effect waves-light red center-align"><%= button_to "-", cart_path(custom_id: candy.id, operator: "-"), method: :put unless quantity == 1 %></a></td>
      </tr>
    <% end if @cart.contents["custom"]%>
    </tbody>
    </table>
    <h4>Total Price: <%= @cart.total_cost %></h4>
    <a class="waves-effect waves-light btn red"><%= button_to "Submit order", orders_path(contents: @cart.contents) %></a>
    <% else %>
      <h2>You have no items in your cart</h2>
    <% end %>
</div>